####################################
#            Networks              #
####################################

networks:
  t2_proxy:
    external: true
    name: t2_proxy
  default:
    driver: bridge


####################################
#            Services              #
####################################

services:
  # All services / apps go below this line

 # Research References
  site-ref:
    container_name: DrPM-ref
    image: trafex/php-nginx:latest
    restart: unless-stopped
    networks:
      - t2_proxy
    volumes:
      - $DOCKERDIR/sites/research-reference/_site:/var/www/html
    labels:
      - "traefik.enable=true"
      #### Research Reference#################################################
      - "traefik.http.routers.nginx-research-ref.entrypoints=https"
      - "traefik.http.routers.nginx-research-ref.tls=true"
      - "traefik.http.routers.nginx-research-ref.rule=Host(`ref.$DOMAINNAME`)"
      - "traefik.http.routers.nginx-research-ref.middlewares=chain-no-auth@file"
      - "traefik.http.routers.nginx-research-ref.service=nginx-ref-svc"
      - "traefik.http.services.nginx-ref-svc.loadbalancer.server.port=8080"

 # Research References
  prrx1:
    container_name: Notebook-Prrx1
    image: trafex/php-nginx:latest
    restart: unless-stopped
    networks:
      - t2_proxy
    volumes:
      - $DOCKERDIR/sites/prrx1-notebook/_site:/var/www/html
    labels:
      - "traefik.enable=true"
      #### Prrx1  #############################################################
      - "traefik.http.routers.nginx-prrx1-rtr.entrypoints=https"
      - "traefik.http.routers.nginx-prrx1-rtr.tls=true"
      - "traefik.http.routers.nginx-prrx1-rtr.rule=Host(`prrx1.$DOMAINNAME`)"
      - "traefik.http.routers.nginx-prrx1-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.nginx-prrx1-rtr.service=nginx-prrx1-svc"
      - "traefik.http.services.nginx-prrx1-svc.loadbalancer.server.port=8080"


 # BFGI Notebook
  bfgi:
    container_name: Notebook-BFGI
    image: trafex/php-nginx:latest
    restart: unless-stopped
    networks:
      - t2_proxy
    volumes:
      - $DOCKERDIR/sites/bfgi-notebook/_site:/var/www/html
    labels:
      - "traefik.enable=true"
      #### BFGI  #############################################################
      - "traefik.http.routers.nginx-bfgi-rtr.entrypoints=https"
      - "traefik.http.routers.nginx-bfgi-rtr.tls=true"
      - "traefik.http.routers.nginx-bfgi-rtr.rule=Host(`bfgi.$DOMAINNAME`)"
      - "traefik.http.routers.nginx-bfgi-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.nginx-bfgi-rtr.service=nginx-bfgi-svc"
      - "traefik.http.services.nginx-bfgi-svc.loadbalancer.server.port=8080"