####################################
#            Networks              #
####################################

networks:
  t2_proxy:
    external: true
    name: t2_proxy
    #Created with docker network create --gateway 10.1.3.1 --subnet 10.1.3.0/24 t2_proxy
  default:
    driver: bridge


####################################
#            Services              #
####################################

services:
  # All services / apps go below this line
