####################################
#            Networks              #
####################################

networks:
  traefik_external:
    external: true
    name: traefik_external
  default:
    driver: bridge


####################################
#            Services              #
####################################

services:
  # All services / apps go below this line

 # Research References
  site-ref:
    container_name: DrPM-ref
    image: trafex/php-nginx:latest
    restart: unless-stopped
    networks:
      - traefik_external
    volumes:
      - $DOCKERDIR/sites/research-reference/_site:/var/www/html
    labels:
      - "traefik.enable=true"
      #### Research Reference#################################################
      - "traefik.http.routers.nginx-research-ref.entrypoints=https"
      - "traefik.http.routers.nginx-research-ref.tls=true"
      - "traefik.http.routers.nginx-research-ref.rule=Host(`ref.$DOMAINNAME`)"
      - "traefik.http.routers.nginx-research-ref.middlewares=chain-no-auth@file"
      - "traefik.http.routers.nginx-research-ref.service=nginx-ref-svc"
      - "traefik.http.services.nginx-ref-svc.loadbalancer.server.port=8080"

 # Research References
  prrx1:
    container_name: Notebook-Prrx1
    image: trafex/php-nginx:latest
    restart: unless-stopped
    networks:
      - traefik_external
    volumes:
      - $DOCKERDIR/sites/prrx1-notebook/_site:/var/www/html
    labels:
      - "traefik.enable=true"
      #### Prrx1  #############################################################
      - "traefik.http.routers.nginx-prrx1-rtr.entrypoints=https"
      - "traefik.http.routers.nginx-prrx1-rtr.tls=true"
      - "traefik.http.routers.nginx-prrx1-rtr.priority=80"
      - "traefik.http.routers.nginx-prrx1-rtr.rule=Host(`prrx1.$DOMAINNAME`)"
      - "traefik.http.routers.nginx-prrx1-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.nginx-prrx1-rtr.service=nginx-prrx1-svc"
      - "traefik.http.services.nginx-prrx1-svc.loadbalancer.server.port=8080"


 # BFGI Notebook
  bfgi:
    container_name: Notebook-BFGI
    image: trafex/php-nginx:latest
    restart: unless-stopped
    networks:
      - traefik_external
    volumes:
      - $DOCKERDIR/sites/bfgi-notebook/_site:/var/www/html
    labels:
      - "traefik.enable=true"
      #### BFGI  #############################################################
      - "traefik.http.routers.nginx-bfgi-rtr.entrypoints=https"
      - "traefik.http.routers.nginx-bfgi-rtr.tls=true"
      - "traefik.http.routers.nginx-bfgi-rtr.priority=80"
      - "traefik.http.routers.nginx-bfgi-rtr.rule=Host(`bfgi.$DOMAINNAME`)"
      - "traefik.http.routers.nginx-bfgi-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.nginx-bfgi-rtr.service=nginx-bfgi-svc"
      - "traefik.http.services.nginx-bfgi-svc.loadbalancer.server.port=8080"


#  # OA-PTOA Notebook
#   oaptoa:
#     container_name: Notebook-OA-PTOA
#     image: trafex/php-nginx:latest
#     restart: unless-stopped
#     networks:
#       - traefik_external
#     volumes:
#       - $DOCKERDIR/sites/oa-ptoa-notebook/_site:/var/www/html
#     labels:
#       - "traefik.enable=true"
#       #### OA-PTOA  #############################################################
#       - "traefik.http.routers.nginx-oaptoa-rtr.entrypoints=https"
#       - "traefik.http.routers.nginx-oaptoa-rtr.tls=true"
#       - "traefik.http.routers.nginx-oaptoa-rtr.priority=80"
#       - "traefik.http.routers.nginx-oaptoa-rtr.rule=Host(`oaptoa.$DOMAINNAME`)"
#       - "traefik.http.routers.nginx-oaptoa-rtr.middlewares=chain-authelia@file"
#       - "traefik.http.routers.nginx-oaptoa-rtr.service=nginx-oaptoa-svc"
#       - "traefik.http.services.nginx-oaptoa-svc.loadbalancer.server.port=8080"