version: "2"

networks:
  t2_proxy:
    external:
      name: t2_proxy
  default:
    driver: bridge
    
services:
  mariadbbb:
    image: "docker.io/bitnami/mariadb:10.3-debian-10"
    container_name: maria-matomo
    networks:
      t2_proxy:
         ipv4_address: 10.1.2.81
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=1234567890
      - MARIADB_USER=bn_matomo
      - MARIADB_DATABASE=bitnami_matomo
      - MARIADB_MASTER_PORT_NUMBER=3307
      # Flag necessary for the database max allowed packet check
      # https://matomo.org/faq/troubleshooting/faq_183/
      - MARIADB_EXTRA_FLAGS=--max_allowed_packet=64MB
    volumes:
      - "/home/pranav/personal-website/matomo4/mariadb:/bitnami/mariadb"
  matomo:
    image: "docker.io/bitnami/matomo:4-debian-10"
    container_name: matomo
    # ports:
      # - "1880:8080"
      # - "1881:8443"
    networks:
      t2_proxy:
         ipv4_address: 10.1.2.80
    environment:
      - MATOMO_DATABASE_HOST=mariadb
      - MATOMO_DATABASE_PORT_NUMBER=3307
      - MATOMO_DATABASE_USER=root
      - MATOMO_DATABASE_PASSWORD=1234567890
      - MATOMO_DATABASE_NAME=bitnami_matomo
      - ALLOW_EMPTY_PASSWORD=yes
      - MATOMO_WEBSITE_HOST=https://drpranavmishra.com
      - MATOMO_WEBSITE_NAME=drpranavmishra
    volumes:
      - "/home/pranav/personal-website/matomo4/data:/bitnami/matomo"
    depends_on:
      - mariadbbb
    links:
      - mariadbbb
    labels:  
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.matomo-rtr.entrypoints=https"
      - "traefik.http.routers.matomo-rtr.rule=Host(`matomo.drpranvmishra.com`)"
      - "traefik.http.routers.matomo-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.matomo-rtr.middlewares=middlewares-basic-auth@file"
      # ## HTTP Services
      # - "traefik.http.routers.matomo-rtr.service=matomo-svc"
      # - "traefik.http.services.matomo-svc.loadbalancer.server.port=8080"
# volumes:
#   mariadb_data:
#     driver: local
#   matomo_data:
#     driver: local