repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.6.0
    hooks:
      # Lint files
      - id: check-yaml
        exclude: |
            (?x)^(
                traefik2/traefik-static.yaml
            )$
      - id: check-xml
      - id: check-json

      # Prevent adding private keys in files
      - id: detect-private-key

      # Detect problemmatic refereneced files
      - id: check-symlinks

      # Only use LF line endings
      - id: mixed-line-ending
        args: ["--fix=lf"]

      - id: check-added-large-files
        args: ['--maxkb=1000']

      - id: check-merge-conflict
        # args: ['']