version: '3.3'
services:
  send:
    ports:
      - '80:80'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
    restart: always
    network_mode: host
    container_name: send
    environment:
      - NODE_ENV=production
        # - S3_BUCKET=testpilot-p2p-dev
        # - REDIS_HOST=dyf9s2r4vo3.bolxr4.0001.usw2.cache.amazonaws.com
        # - 'SENTRY_CLIENT=https://51e23d7263e348a7a3b90a5357c61cb2@sentry.prod.mozaws.net/168'
        # - 'SENTRY_DSN=https://51e23d7263e348a7a3b90a5357c61cb2:65e23d7263e348a7a3b90a5357c61c44@sentry.prod.mozaws.net/168'
      - 'BASE_URL=https://send.drpranavmishra.com'
    image: registry.gitlab.com/timvisee/send:latest
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.ffsend-rtr.entrypoints=https"
      - "traefik.http.routers.ffsend-rtr.tls=true"
      - "traefik.http.routers.ffsend-rtr.rule=Host(`send.drpranavmishra.com`)"
      ## Middlewares
      - "traefik.http.routers.ffsend-rtr.middlewares=middlewares=chain-visitor-auth@file"
      ## HTTP Services
      - "traefik.http.routers.ffsend-rtr.service=ffsend-svc"
      - "traefik.http.services.ffsend-svc.loadbalancer.server.port=80"