[http.routers]
  [http.routers.matomo-rtr]
      entryPoints = ["https"]
      rule = "Host(`matomo.drpranavmishra.com`)"
      service = "matomo-svc"
      middlewares = ["chain-basic-auth"]
      [http.routers.matomo-rtr.tls]
        certresolver = "dns-cloudflare"

[http.services]
  [http.services.matomo-svc]
    [http.services.matomo-svc.loadBalancer]
      passHostHeader = true
      [[http.services.matomo-svc.loadBalancer.servers]]
        url = "http://10.1.2.80:8080" # or whatever your external host's IP:port is
