# Dynamic Configuration for Traefik Dashboard
http:
  routers:
    dashboard:
      rule: Host(`traefik.drpranavmishra.com`) #&& (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      service: api@internal
      middlewares:
        - chain-authelia
      tls:
        certresolver: dns-cloudflare