# Traefik Static Configuration

core:
  defaultRuleSyntax: v2

global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  matrix-internal-matrix-client-api:
    address: ":8008"

api:
  dashboard: true
  insecure: false

log:
  level: ERROR

accessLog:
  filePath: /traefik-access.log
  bufferingSize: 100
  filters:
    statusCodes: ["400-520"]

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    defaultRule: "Host(`{{ index .Labels \"com.docker.compose.service\" }}.$DOMAINNAME`)"
    network: t2_proxy
    swarmMode: false
  file:
    directory: /rules
    watch: true

certificatesResolvers:
  dns-cloudflare:
    acme:
      email: $CLOUDFLARE_EMAIL
      storage: /acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
